### ISSUE TITLE
20210606 필요 화면 및 기능 정리

### ISSUE THREAD

**Issue by jaehleeee** [jaehleeee/albadon#23]
### 객체 레벨
 * 레벨1 - 보스
 * 레벨2 - 스토어
 * 레벨3 - 매장정보 / 직원정보 / 캘린더 / 근무이력

### 레벨3 메뉴 (실제 개발 요소)
 * (우선순위1) - `월급계산` : 직원들의 근무 이력 및 주급과 월급 계산
     * 목표 기한 7월 첫째주
 * (우선순위2) - `직원관리` : 해당 스토어에 소속된 직원 리스트와 정보 제공,  직원들의 계약 근무가 정리된 주간 시간 테이블
 * (우선순위3) - `직원관리` 신규 직원 추가 : 신규 직원을 추가하고, 계약된 근무 정보를 저장한다.
 * (우선순위4) - `캘린더` : 월별 직원들의 근무 시간표
 * (우선순위5) - `매장정보` : 해당 매장에 대한 기본적인 정보 제공

### 추가 기능
 * 근무이력 및 급여(주급+월급) 엑셀 다운로드
 
 @ga0hyeon @Hekatons @jaybe-park

**Comment by jaybe-park** [comment]
# TODO:
@jaybe-park 
* 테이블 확정
* 샘플 데이터 생성
* 집에 노는 컴퓨터에 dev db 구축
* 배포 시스템 구축

@Hekatons @ga0hyeon 
* 페이지 구성 완료
* API 설계
* 페이지 개발

@jaehleeee 
* API 설계

# API 설계
* 특정 매장에 대한 전체 직원 정보 조회
  * request - 매장id
  * response - 직원 목록(list) - 직원id, contract_id, 이름 등
  * contract를 조회한 다음 employee와 조합해서 응답해야됨
* 특정 매장의 특정 직원에 대한 contract_detail 정보 조회
  * request - contract_id
  * response - 요일별 근무시간, 시급 등
* 특정 매장의 특정 직원에 대한 특정 월 근무이력 정보 조회
  * request - contract_id, YYYY-MM
  * response - 요일별 근무시간 등
  * 주급/월급 계산은 front에서 하는 걸로

다음 모임은 6/10 목요일 오후 9시에 하는걸로

**Comment by jaehleeee** [comment]
### 특정 boss가 가진 store 리스트 조회
### work 근무이력 insert / update
